version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/medical-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-medical_db}
      - DB_SSL_MODE=${DB_SSL_MODE:-disable}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - TOKEN_HOUR_LIFESPAN=${TOKEN_HOUR_LIFESPAN:-24}
      - ENV=${ENV:-production}
      - FRONTEND_URL=${FRONTEND_URL:-https://medical-app.vercel.app}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-medical_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: 