services:
  - type: web
    name: medical-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://medical-backend.onrender.com
      - key: NODE_ENV
        value: production

  - type: web
    name: medical-backend
    env: go
    buildCommand: cd backend && go mod download && go build -o main ./cmd/api/main.go
    startCommand: cd backend && ./main
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: TOKEN_HOUR_LIFESPAN
        value: 24
      - key: ENV
        value: production
      - key: FRONTEND_URL
        value: https://medical-frontend.onrender.com

databases:
  - name: medical-db
    databaseName: medical_db
    user: postgres
    plan: free 